Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -49,4 +49,28 @@ jobs:
       - name: List build directory for verification
         run: ls -R build/
 
+  quality_gate_check:
+    runs-on: ubuntu-latest
+    needs: test   # Ce job dépend du job 'test'
 
+    steps:
+      # Récupérer le code source (étape nécessaire pour récupérer l'environnement du repo)
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # Installer jq
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
+      # Vérifier le statut du Quality Gate
+      - name: Check Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=inessBenguiar_GitActions-test" \
+          | jq -r '.projectStatus.status')
+          echo "Quality Gate Status: $STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed!"
+            exit 1
+          fi
